### ISSUE TITLE
Doesn't work for my psks

### ISSUE THREAD

**Issue by Khadep** [kuzmin-no/Cisco-AireOS-WLC-config-decryption-tool#1]
This hasn't worked for me. I have the following on a controller for a wlan and im expecting the psk to be xxxxxx but it doesnt give me the correct hex for that PSK. 

config wlan security wpa akm psk set-key hex encrypt 1 e672ac0e36cdf0ea9da9cf599086a469 35fad8bd7b839da5defd5d2137b125be31ce86c7 48 49673f0b3ab28908105dbc78303866963098937488148b3659ff7d638a4b49fcd983b68d9e3afdc8014cc5e7d210a67a0000000000000000000000000000000000000000000000000000000000000000167972400000000000000206000000000606000100000000158a2b600000000010680960000000000000020600000000132f000000000000158a2b6000000000 16

Any Ideas?

**Comment by kuzmin-no** [comment]
Hi, PSK hex is the result of PBKDF2 (Password-Based Key Derivation Function) function, which takes passphrase (PSK ASCII) and salt (SSID/WLAN name) as input parameters. When migrating PSK hex to the new WLC, the SSID (WLAN name) must be exactly the same. From the confituraion you provided can only be obtained WLAN ID (16) and PSK hex, but not the SSID. SSID must present in the configuration file as a separate configuration command "config wlan create 16  xxxxxxxxx"

WLAN ID: 16, PSK hex: 41f45353f2ece2286681995186522aaa2e5e1c50cee422f70359f8495d42a876

**Comment by Khadep** [comment]
That was just a snippet. Here is the full wlan config. I had a different SSID name on the new controller and thought I could use the same psk hex. I didn't know that the SSID was also used to decrypt the hash on the controller side. Thank You!

! config wlan create 16 xxxx xxxx
! config wlan enable 16
! config wlan broadcast-ssid enable 16
! config wlan security wpa enable 16
! config wlan security wpa akm 802.1x disable 16
! config wlan security wpa akm psk enable 16
! config wlan security wpa akm psk set-key hex encrypt 1 e672ac0e36cdf0ea9da9cf599086a469 35fad8bd7b839da5defd5d2137b125be31ce86c7 48 49673f0b3ab28908105dbc78303866963098937488148b3659ff7d638a4b49fcd983b68d9e3afdc8014cc5e7d210a67a0000000000000000000000000000000000000000000000000000000000000000167972400000000000000206000000000606000100000000158a2b600000000010680960000000000000020600000000132f000000000000158a2b6000000000 16

**Comment by Khadep** [comment]
That was just a snippet. Here is the full wlan config. I had a different SSID name on th e new controller and thought I could use the same psk hex. I didn't know that the SSID was also used to decrypt the hash on the controller side. Thank You!

! config wlan create 16 UrbanPrep UrbanPrep
! config wlan enable 16
! config wlan broadcast-ssid enable 16
! config wlan security wpa enable 16
! config wlan security wpa akm 802.1x disable 16
! config wlan security wpa akm psk enable 16
! config wlan security wpa akm psk set-key hex encrypt 1 e672ac0e36cdf0ea9da9cf599086a469 35fad8bd7b839da5defd5d2137b125be31ce86c7 48 49673f0b3ab28908105dbc78303866963098937488148b3659ff7d638a4b49fcd983b68d9e3afdc8014cc5e7d210a67a0000000000000000000000000000000000000000000000000000000000000000167972400000000000000206000000000606000100000000158a2b600000000010680960000000000000020600000000132f000000000000158a2b6000000000 16

**Comment by Khadep** [comment]
That was just a snippet. Here is the full wlan config. I had a different SSID name on the new controller and thought I could use the same psk hex. I didn't know that the SSID was also used to decrypt the hash on the controller side. Thank You!

! config wlan create 16 UrbanPrep UrbanPrep
! config wlan enable 16
! config wlan broadcast-ssid enable 16
! config wlan security wpa enable 16
! config wlan security wpa akm 802.1x disable 16
! config wlan security wpa akm psk enable 16
! config wlan security wpa akm psk set-key hex encrypt 1 e672ac0e36cdf0ea9da9cf599086a469 35fad8bd7b839da5defd5d2137b125be31ce86c7 48 49673f0b3ab28908105dbc78303866963098937488148b3659ff7d638a4b49fcd983b68d9e3afdc8014cc5e7d210a67a0000000000000000000000000000000000000000000000000000000000000000167972400000000000000206000000000606000100000000158a2b600000000010680960000000000000020600000000132f000000000000158a2b6000000000 16
